const game = [
    {
        gameId: 1,
        gameName: "Elden Ring",
        gameDesc: "THE NEW FANTASY ACTION RPG. Rise, Tarnished, and be guided by grace to brandish the power of the Elden Ring and become an Elden Lord in the Lands Between.",
        gameArt: "./img/elden-ring.jpg",
        gameArt1: "./img/elden-ring1.jpg",
        gameArt2: "./img/elden-ring2.jpg",
        gameArt3: "./img/elden-ring3.jpg",
        gameArt4: "./img/elden-ring4.jpeg",
        gamePrice: 59.99,
    },
    {
        gameId: 2,
        gameName: "Among Us",
        gameDesc: "THE NEW FANTASY ACTION RPG. Rise, Tarnished, and be guided by grace to brandish the power of the Elden Ring and become an Elden Lord in the Lands Between.",
        gameArt: "./img/among-us.png",
        gameArt1: "./img/among-us-gameplay.jpg",
        gameArt2: "./img/among-us-kill.jpg",
        gameArt3: "./img/among-us-chat.png",
        gameArt4: "./img/among-us-room.jpg",
        gamePrice: 59.99,
    },
    {
        gameId: 3,
        gameName: "Party Animal",
        gameDesc: "THE NEW FANTASY ACTION RPG. Rise, Tarnished, and be guided by grace to brandish the power of the Elden Ring and become an Elden Lord in the Lands Between.",
        gameArt: "./img/party-animal.jpg",
        gameArt1: "./img/party-animal-gameplay.jpg",
        gameArt2: "./img/party-animal-gameplay2.jpg",
        gameArt3: "./img/party-animal-gameplay3.jpg",
        gameArt4: "./img/party-animal-gameplay4.jpg",
        gamePrice: 59.99,
    },
    {
        gameId: 4,
        gameName: "Don't scream",
        gameDesc: "THE NEW FANTASY ACTION RPG. Rise, Tarnished, and be guided by grace to brandish the power of the Elden Ring and become an Elden Lord in the Lands Between.",
        gameArt: "./img/don't-scream.jpg",
        gameArt1: "./img/don't-scream1.jpg",
        gameArt2: "./img/don't-scream2.jpg",
        gameArt3: "./img/don't-scream3.jpg",
        gameArt4: "./img/don't-scream4.jpg",
        gamePrice: 59.99,
    },
    {
        gameId: 5,
        gameName: "Raft",
        gameDesc: "THE NEW FANTASY ACTION RPG. Rise, Tarnished, and be guided by grace to brandish the power of the Elden Ring and become an Elden Lord in the Lands Between.",
        gameArt: "./img/raft.jpg",
        gameArt1: "./img/raft-gameplay1.jpg",
        gameArt2: "./img/raft-gameplay2.jpg",
        gameArt3: "./img/raft-gameplay3.jpg",
        gameArt4: "./img/raft-gameplay4.jpg",
        gamePrice: 59.99,
    },
    {
        gameId: 6,
        gameName: "Little Nightmares",
        gameDesc: "THE NEW FANTASY ACTION RPG. Rise, Tarnished, and be guided by grace to brandish the power of the Elden Ring and become an Elden Lord in the Lands Between.",
        gameArt: "./img/little-nightmares.jpg",
        gameArt1: "./img/little-nightmares-gameplay1.jpg",
        gameArt2: "./img/little-nightmares-gameplay2.jpg",
        gameArt3: "./img/little-nightmares-gameplay3.jpg",
        gameArt4: "./img/little-nightmares-gameplay4.jpg",
        gamePrice: 59.99,
    },

];

export { game };